spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
#      dialect: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  datasource:
    hikari:
      maximum-pool-size: 4
    url: jdbc:postgresql://localhost:5432/mypostgresdb
    username: reddyong
    password: reddyong1234!@#$
    driver-class-name: org.postgresql.Driver


jwt:
  secret.key: fastcampus.sns-project-2024.secret_key.myReddyongSecretKey!@#$1234
  token.expired-time-ms: 2592000000
