server:
  port: 8081

spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  datasource:
    hikari:
      maximum-pool-size: 4
    url: jdbc:postgresql://localhost:5432/mypostgresdb
    username: reddyong
    password: reddyong1234!@#$
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: alarm
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
    listener:
      ack-mode: MANUAL
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    topic:
      alarm: fc8-sns


jwt:
  secret.key: fastcampus.sns-project-2024.secret_key.myReddyongSecretKey!@#$1234
  token.expired-time-ms: 2592000000

